'''
All the tool configs are stuck here, the name of the variable matches
the tool name,
tool_config=getattr(tool_configs, 'ols_ped')
'''
tools=['ols_ped','ols_bike', 'binomial_ped', 'binomial_bike']

ols_ped={'info': {'name': 'Pedestrian Volume (OLS Method, Minnesota)',
                 'text': 'Given a set of statistical parameters, this ' +  \
                         'model estimates non-motorized travel using ' +   \
                         'ordinary least-squares and negative binomial ' + \
                         'counts from hourly counts.  Provide the ' +      \
                         'required statistical parameters to execute ' +   \
                         'the model.',
         'version': '0.1'},
         'sample': {},
         'documentation': {'links': {'Minnesota Pedestrian Ordinary Least-Squares Model': None}},
         'input': {'description': 'The indicated properties should be ' +   \
                                  'provided for each row of input data. ' + \
                                  ' Omitting a property will result in ' +  \
                                  'an incomplete execution of the model ' + \
                                  'as the missing property and its ' +      \
                                  'coefficients will be omitted from the' + \
                                  ' model entirely.',
                   'properties': {'constant': {'description': 'Constant value',
                                               'type': 'number',
                                               'default': 788.6,
                                               'required': True},
                                  'Pctnonwhite': {'description': 'Percentage of neighborhood residents that are non-white',
                                                  'type': 'property',
                                                  'required': True, },
                                  'PctU5_O65': {'description': 'Percentage of neighborhood residents over 65 or under 5',
                                                'type': 'property',
                                                'required': True,},
                                  'Pctw4ormore': {'description': 'Percentage of neighborhood residents with a college education',
                                                  'type': 'property',
                                                  'required': True,},
                                  'MedHHInc': {'description': 'Median household income',
                                               'type': 'property',
                                               'required': True,},
                                  'Crime': {'description': 'Average number of violent crimes/year',
                                            'type': 'property',
                                            'required': True,},
                                  'PDperkm2': {'description': 'Population density in persons per square kilometer',
                                               'type': 'property',
                                               'required': True,},
                                  'LUMix': {'description': 'Measure of mixing of land uses (range 0-1)',
                                            'type': 'property',
                                            'required': True,},
                                  'WatDist_km': {'description': 'Distance from nearest body of water, in kilometers',
                                                 'type': 'property',
                                                 'required': True,},
                                  'CBDdist_km': {'description': 'Distance from central business district, kilometers',
                                                 'type': 'property',
                                                 'required': True,},
                                  'EmployAccess': {'description': 'Number of jobs accessible via transit.',
                                                   'type': 'property',
                                                   'required': True,},
                                  'Tmax': {'description': 'Recorded daily high temperature',
                                           'type': 'property',
                                           'required': True,},
                                  'Precip': {'description': 'Recorded precipitation',
                                             'type': 'property',
                                             'required': True,},
                                  'University': {'description': 'University district (1/0)',
                                                 'type': 'property',
                                                 'required': True,},
                                  'BusRoute': {'description': 'Presence of one of more bus routes (1/0)',
                                               'type': 'property',
                                               'required': True,},
                                  'Principal': {'description': 'Principal arterial street (1/0)',
                                                'type': 'property',
                                                'required': True,},
                                  'Arterial': {'description': 'Arterial street (1/0)',
                                               'type': 'property',
                                               'required': True,},
                                  'Collector': {'description': 'Collector street  (1/0)',
                                                'type': 'property',
                                                'required': True,},
                                  'Local': {'description': 'Local street (1/0)',
                                            'type': 'property',
                                            'required': True,},
                                  'OnstreetFacility': {'description': 'On street bicycle facility (1/0)',
                                                       'type': 'property',
                                                       'required': True,},
                                  'OffstreetTrail': {'description': 'Off-street trail (1/0)',
                                                     'type': 'property',
                                                     'required': True,},
                                  'Year': {'description': 'Level variable indicating year count occurred (offset from year 2007)',
                                           'type': 'property',
                                           'required': True,},
                                  'Pctnonwhite_coeff': {'description': 'Coefficient used for OLS Pctnonwhite property',
                                                        'type': 'number',
                                                        'default': -29.8,
                                                        'required': True,},
                                  'PctU5_O65_coeff': {'description': 'Coefficient used for OLS PctU5_O65 property',
                                                      'type': 'number',
                                                      'default': 32.5,
                                                      'required': True,},
                                  'Pctw4ormore_coeff': {'description': 'Coefficient used for OLS Pctw4ormore property',
                                                        'type': 'number',
                                                        'default': 371.4,
                                                        'required': True,},
                                  'MedHHInc_coeff': {'description': 'Coefficient used for OLS MedHHInc property',
                                                     'type': 'number',
                                                     'default': 2.1,
                                                     'required': True,},
                                  'Crime_coeff': {'description': 'Coefficient used for OLS Crime property',
                                                  'type': 'number',
                                                  'default': 2.9,
                                                  'required': True,},
                                  'PDperkm2_coeff': {'description': 'Coefficient used for OLS PDperkm2 property',
                                                     'type': 'number',
                                                     'default': -0.035,
                                                     'required': True,},
                                  'LUMix_coeff': {'description': 'Coefficient used for OLS LUMix property',
                                                  'type': 'number',
                                                  'default': -919.9,
                                                  'required': True,},
                                  'WatDist_km_coeff': {'description': 'Coefficient used for OLS WatDist_km property',
                                                       'type': 'number',
                                                       'default': -21.6,
                                                       'required': True,},
                                  'CBDdist_km_coeff': {'description': 'Coefficient used for OLS CBDdist_km property',
                                                       'type': 'number',
                                                       'default': -40.3,
                                                       'required': True,},
                                  'EmployAccess_coeff': {'description': 'Coefficient used for OLS EmployAccess property',
                                                         'type': 'number',
                                                         'default': 0,
                                                         'required': True,},
                                  'Tmax_coeff': {'description': 'Coefficient used for OLS Tmax property',
                                                 'type': 'number',
                                                 'default': -26.0,
                                                 'required': True,},
                                  'Precip_coeff': {'description': 'Coefficient used for OLS Precip property',
                                                   'type': 'number',
                                                   'default': -127.8,
                                                   'required': True,},
                                  'University_coeff': {'description': 'Coefficient used for OLS University property',
                                                       'type': 'number',
                                                       'default': 0,
                                                       'required': True,},
                                  'BusRoute_coeff': {'description': 'Coefficient used for OLS BusRoute property',
                                                     'type': 'number',
                                                     'default': 100.3,
                                                     'required': True,},
                                  'Principal_coeff': {'description': 'Coefficient used for OLS Principal property',
                                                      'type': 'number',
                                                      'default': 66.4,
                                                      'required': True,},
                                  'Arterial_coeff': {'description': 'Coefficient used for OLS Arterial property',
                                                     'type': 'number',
                                                     'default': 391.8,
                                                     'required': True,},
                                  'Collector_coeff': {'description': 'Coefficient used for OLS Collector property',
                                                      'type': 'number',
                                                      'default': 611.1,
                                                      'required': True,},
                                  'Local_coeff': {'description': 'Coefficient used for OLS Local property',
                                                  'type': 'number',
                                                  'default': 1,
                                                  'required': True,},
                                  'OnstreetFacility_coeff': {'description': 'Coefficient used for OLS OnstreetFacility property',
                                                             'type': 'number',
                                                             'default': 0,
                                                             'required': True,},
                                  'OffstreetTrail_coeff': {'description': 'Coefficient used for OLS OffstreetTrail property',
                                                           'type': 'number',
                                                           'default': 253.8,
                                                           'required': True,},
                                  'Year_coeff': {'description': 'Coefficient used for OLS Year property',
                                                 'type': 'number',
                                                 'default': -5.9,
                                                 'required': True,},
                                 }}
        }

ols_bike=  {'info': {'name': 'Bicycle Volume (OLS Method, Minnesota)',
                     'text': 'Given a set of statistical parameters, this ' +  \
                             'model estimates non-motorized travel using ' +   \
                             'ordinary least-squares and negative binomial ' + \
                             'counts from hourly counts.  Provide the ' +      \
                             'required statistical parameters to execute ' +   \
                             'the model.',
             'version': '0.1'},
             'sample': {},
             'documentation': {'links': {'Minnesota Cycling OLS Model': None}},
             'input': {'description': 'The indicated properties should be ' +   \
                                      'provided for each row of input data. ' + \
                                      ' Omitting a property will result in ' +  \
                                      'an incomplete execution of the model ' + \
                                      'as the missing property and its ' +      \
                                      'coefficients will be omitted from the' + \
                                      ' model entirely.',
                       'properties': {'constant': {'description': 'Constant value',
                                                   'type': 'number',
                                                   'default': -20.9,
                                                   'required': True},
                                      'Pctnonwhite': {'description': 'Percentage of neighborhood residents that are non-white',
                                                      'type': 'property',
                                                      'required': True, },
                                      'PctU5_O65': {'description': 'Percentage of neighborhood residents over 65 or under 5',
                                                    'type': 'property',
                                                    'required': True,},
                                      'Pctw4ormore': {'description': 'Percentage of neighborhood residents with a college education',
                                                      'type': 'property',
                                                      'required': True,},
                                      'MedHHInc': {'description': 'Median household income',
                                                   'type': 'property',
                                                   'required': True,},
                                      'Crime': {'description': 'Average number of violent crimes/year',
                                                'type': 'property',
                                                'required': True,},
                                      'PDperkm2': {'description': 'Population density in persons per square kilometer',
                                                   'type': 'property',
                                                   'required': True,},
                                      'LUMix': {'description': 'Measure of mixing of land uses (range 0-1)',
                                                'type': 'property',
                                                'required': True,},
                                      'WatDist_km': {'description': 'Distance from nearest body of water, in kilometers',
                                                     'type': 'property',
                                                     'required': True,},
                                      'CBDdist_km': {'description': 'Distance from central business district, kilometers',
                                                     'type': 'property',
                                                     'required': True,},
                                      'EmployAccess': {'description': 'Number of jobs accessible via transit.',
                                                       'type': 'property',
                                                       'required': True,},
                                      'Tmax': {'description': 'Recorded daily high temperature',
                                               'type': 'property',
                                               'required': True,},
                                      'Precip': {'description': 'Recorded precipitation',
                                                 'type': 'property',
                                                 'required': True,},
                                      'University': {'description': 'University district (1/0)',
                                                     'type': 'property',
                                                     'required': True,},
                                      'BusRoute': {'description': 'Presence of one of more bus routes (1/0)',
                                                   'type': 'property',
                                                   'required': True,},
                                      'Principal': {'description': 'Principal arterial street (1/0)',
                                                    'type': 'property',
                                                    'required': True,},
                                      'Arterial': {'description': 'Arterial street (1/0)',
                                                   'type': 'property',
                                                   'required': True,},
                                      'Collector': {'description': 'Collector street  (1/0)',
                                                    'type': 'property',
                                                    'required': True,},
                                      'Local': {'description': 'Local street (1/0)',
                                                'type': 'property',
                                                'required': True,},
                                      'OnstreetFacility': {'description': 'On street bicycle facility (1/0)',
                                                           'type': 'property',
                                                           'required': True,},
                                      'OffstreetTrail': {'description': 'Off-street trail (1/0)',
                                                         'type': 'property',
                                                         'required': True,},
                                      'Year': {'description': 'Level variable indicating year count occurred (offset from year 2007)',
                                               'type': 'property',
                                               'required': True,},
                                      'Pctnonwhite_coeff': {'description': 'Coefficient used for OLS Pctnonwhite property',
                                                            'type': 'number',
                                                            'default': 189.7,
                                                            'required': True,},
                                      'PctU5_O65_coeff': {'description': 'Coefficient used for OLS PctU5_O65 property',
                                                          'type': 'number',
                                                          'default': 461.7,
                                                          'required': True,},
                                      'Pctw4ormore_coeff': {'description': 'Coefficient used for OLS Pctw4ormore property',
                                                            'type': 'number',
                                                            'default': 688.9,
                                                            'required': True,},
                                      'MedHHInc_coeff': {'description': 'Coefficient used for OLS MedHHInc property',
                                                         'type': 'number',
                                                         'default': -4.1,
                                                         'required': True,},
                                      'Crime_coeff': {'description': 'Coefficient used for OLS Crime property',
                                                      'type': 'number',
                                                      'default': -0.2,
                                                      'required': True,},
                                      'PDperkm2_coeff': {'description': 'Coefficient used for OLS PDperkm2 property',
                                                         'type': 'number',
                                                         'default': -0.0076,
                                                         'required': True,},
                                      'LUMix_coeff': {'description': 'Coefficient used for OLS LUMix property',
                                                      'type': 'number',
                                                      'default': 12.9,
                                                      'required': True,},
                                      'WatDist_km_coeff': {'description': 'Coefficient used for OLS WatDist_km property',
                                                           'type': 'number',
                                                           'default': 17.6,
                                                           'required': True,},
                                      'CBDdist_km_coeff': {'description': 'Coefficient used for OLS CBDdist_km property',
                                                           'type': 'number',
                                                           'default': -55.2,
                                                           'required': True,},
                                      'EmployAccess_coeff': {'description': 'Coefficient used for OLS EmployAccess property',
                                                             'type': 'number',
                                                             'default': 0.0011,
                                                             'required': True,},
                                      'Tmax_coeff': {'description': 'Coefficient used for OLS Tmax property',
                                                     'type': 'number',
                                                     'default': -2.6,
                                                     'required': True,},
                                      'Precip_coeff': {'description': 'Coefficient used for OLS Precip property',
                                                       'type': 'number',
                                                       'default': -54.3,
                                                       'required': True,},
                                      'University_coeff': {'description': 'Coefficient used for OLS University property',
                                                           'type': 'number',
                                                           'default': 0,
                                                           'required': True,},
                                      'BusRoute_coeff': {'description': 'Coefficient used for OLS BusRoute property',
                                                         'type': 'number',
                                                         'default': 0,
                                                         'required': True,},
                                      'Principal_coeff': {'description': 'Coefficient used for OLS Principal property',
                                                          'type': 'number',
                                                          'default': -115.6,
                                                          'required': True,},
                                      'Arterial_coeff': {'description': 'Coefficient used for OLS Arterial property',
                                                         'type': 'number',
                                                         'default': 140.6,
                                                         'required': True,},
                                      'Collector_coeff': {'description': 'Coefficient used for OLS Collector property',
                                                          'type': 'number',
                                                          'default': 3.3,
                                                          'required': True,},
                                      'Local_coeff': {'description': 'Coefficient used for OLS Local property',
                                                      'type': 'number',
                                                      'default': 1,
                                                      'required': True,},
                                      'OnstreetFacility_coeff': {'description': 'Coefficient used for OLS OnstreetFacility property',
                                                                 'type': 'number',
                                                                 'default': 98.8,
                                                                 'required': True,},
                                      'OffstreetTrail_coeff': {'description': 'Coefficient used for OLS OffstreetTrail property',
                                                               'type': 'number',
                                                               'default': 690.8,
                                                               'required': True,},
                                      'Year_coeff': {'description': 'Coefficient used for OLS Year property',
                                                     'type': 'number',
                                                     'default': 61.6,
                                                     'required': True,},
                                     }}
            }


binomial_ped=  {'info': {'name': 'Pedestrian Volume (Binomial Method, Minnesota)',
                         'text': 'Given a set of statistical parameters, this ' +  \
                                 'model estimates non-motorized travel using ' +   \
                                 'ordinary least-squares and negative binomial ' + \
                                 'counts from hourly counts.  Provide the ' +      \
                                 'required statistical parameters to execute ' +   \
                                 'the model.',
                 'version': '0.1'},
                 'sample': {},
                 'documentation': {'links': {'Minnesota Pedestrian Negative Binomial Model': None}},
                 'input': {'description': 'The indicated properties should be ' +   \
                                          'provided for each row of input data. ' + \
                                          ' Omitting a property will result in ' +  \
                                          'an incomplete execution of the model ' + \
                                          'as the missing property and its ' +      \
                                          'coefficients will be omitted from the' + \
                                          ' model entirely.',
                           'properties': {'constant': {'description': 'Constant value',
                                                       'type': 'number',
                                                       'default': 5.565,
                                                       'required': True},
                                          'Pctnonwhite': {'description': 'Percentage of neighborhood residents that are non-white',
                                                          'type': 'property',
                                                          'required': True, },
                                          'PctU5_O65': {'description': 'Percentage of neighborhood residents over 65 or under 5',
                                                        'type': 'property',
                                                        'required': True,},
                                          'Pctw4ormore': {'description': 'Percentage of neighborhood residents with a college education',
                                                          'type': 'property',
                                                          'required': True,},
                                          'MedHHInc': {'description': 'Median household income',
                                                       'type': 'property',
                                                       'required': True,},
                                          'Crime': {'description': 'Average number of violent crimes/year',
                                                    'type': 'property',
                                                    'required': True,},
                                          'PDperkm2': {'description': 'Population density in persons per square kilometer',
                                                       'type': 'property',
                                                       'required': True,},
                                          'LUMix': {'description': 'Measure of mixing of land uses (range 0-1)',
                                                    'type': 'property',
                                                    'required': True,},
                                          'WatDist_km': {'description': 'Distance from nearest body of water, in kilometers',
                                                         'type': 'property',
                                                         'required': True,},
                                          'CBDdist_km': {'description': 'Distance from central business district, kilometers',
                                                         'type': 'property',
                                                         'required': True,},
                                          'EmployAccess': {'description': 'Number of jobs accessible via transit.',
                                                           'type': 'property',
                                                           'required': True,},
                                          'Tmax': {'description': 'Recorded daily high temperature',
                                                   'type': 'property',
                                                   'required': True,},
                                          'Precip': {'description': 'Recorded precipitation',
                                                     'type': 'property',
                                                     'required': True,},
                                          'University': {'description': 'University district (1/0)',
                                                         'type': 'property',
                                                         'required': True,},
                                          'BusRoute': {'description': 'Presence of one of more bus routes (1/0)',
                                                       'type': 'property',
                                                       'required': True,},
                                          'Principal': {'description': 'Principal arterial street (1/0)',
                                                        'type': 'property',
                                                        'required': True,},
                                          'Arterial': {'description': 'Arterial street (1/0)',
                                                       'type': 'property',
                                                       'required': True,},
                                          'Collector': {'description': 'Collector street  (1/0)',
                                                        'type': 'property',
                                                        'required': True,},
                                          'Local': {'description': 'Local street (1/0)',
                                                    'type': 'property',
                                                    'required': True,},
                                          'OnstreetFacility': {'description': 'On street bicycle facility (1/0)',
                                                               'type': 'property',
                                                               'required': True,},
                                          'OffstreetTrail': {'description': 'Off-street trail (1/0)',
                                                             'type': 'property',
                                                             'required': True,},
                                          'Year': {'description': 'Level variable indicating year count occurred (offset from year 2007)',
                                                   'type': 'property',
                                                   'required': True,},
                                          'Pctnonwhite_coeff': {'description': 'Coefficient used for OLS Pctnonwhite property',
                                                                'type': 'number',
                                                                'default': .743,
                                                                'required': True,},
                                          'PctU5_O65_coeff': {'description': 'Coefficient used for OLS PctU5_O65 property',
                                                              'type': 'number',
                                                              'default': -0.919,
                                                              'required': True,},
                                          'Pctw4ormore_coeff': {'description': 'Coefficient used for OLS Pctw4ormore property',
                                                                'type': 'number',
                                                                'default': 1.391,
                                                                'required': True,},
                                          'MedHHInc_coeff': {'description': 'Coefficient used for OLS MedHHInc property',
                                                             'type': 'number',
                                                             'default': .0004,
                                                             'required': True,},
                                          'Crime_coeff': {'description': 'Coefficient used for OLS Crime property',
                                                          'type': 'number',
                                                          'default': .0002,
                                                          'required': True,},
                                          'PDperkm2_coeff': {'description': 'Coefficient used for OLS PDperkm2 property',
                                                             'type': 'number',
                                                             'default': .00001,
                                                             'required': True,},
                                          'LUMix_coeff': {'description': 'Coefficient used for OLS LUMix property',
                                                          'type': 'number',
                                                          'default': -.532,
                                                          'required': True,},
                                          'WatDist_km_coeff': {'description': 'Coefficient used for OLS WatDist_km property',
                                                               'type': 'number',
                                                               'default': -.116,
                                                               'required': True,},
                                          'CBDdist_km_coeff': {'description': 'Coefficient used for OLS CBDdist_km property',
                                                               'type': 'number',
                                                               'default': -.151,
                                                               'required': True,},
                                          'EmployAccess_coeff': {'description': 'Coefficient used for OLS EmployAccess property',
                                                                 'type': 'number',
                                                                 'default': .000005,
                                                                 'required': True,},
                                          'Tmax_coeff': {'description': 'Coefficient used for OLS Tmax property',
                                                         'type': 'number',
                                                         'default': -0.012,
                                                         'required': True,},
                                          'Precip_coeff': {'description': 'Coefficient used for OLS Precip property',
                                                           'type': 'number',
                                                           'default': -0.150,
                                                           'required': True,},
                                          'University_coeff': {'description': 'Coefficient used for OLS University property',
                                                               'type': 'number',
                                                               'default': 0,
                                                               'required': True,},
                                          'BusRoute_coeff': {'description': 'Coefficient used for OLS BusRoute property',
                                                             'type': 'number',
                                                             'default': .211,
                                                             'required': True,},
                                          'Principal_coeff': {'description': 'Coefficient used for OLS Principal property',
                                                              'type': 'number',
                                                              'default': -.823,
                                                              'required': True,},
                                          'Arterial_coeff': {'description': 'Coefficient used for OLS Arterial property',
                                                             'type': 'number',
                                                             'default': .774,
                                                             'required': True,},
                                          'Collector_coeff': {'description': 'Coefficient used for OLS Collector property',
                                                              'type': 'number',
                                                              'default': .853,
                                                              'required': True,},
                                          'Local_coeff': {'description': 'Coefficient used for OLS Local property',
                                                          'type': 'number',
                                                          'default': 1,
                                                          'required': True,},
                                          'OnstreetFacility_coeff': {'description': 'Coefficient used for OLS OnstreetFacility property',
                                                                     'type': 'number',
                                                                     'default': 0,
                                                                     'required': True,},
                                          'OffstreetTrail_coeff': {'description': 'Coefficient used for OLS OffstreetTrail property',
                                                                   'type': 'number',
                                                                   'default': .190,
                                                                   'required': True,},
                                          'Year_coeff': {'description': 'Coefficient used for OLS Year property',
                                                         'type': 'number',
                                                         'default': .001,
                                                         'required': True,},
                                         }}
                }

binomial_bike= {'info': {'name': 'Bicycle Volume (Binomial Method, Minnesota)',
                         'text': 'Given a set of statistical parameters, this ' +  \
                                 'model estimates non-motorized travel using ' +   \
                                 'ordinary least-squares and negative binomial ' + \
                                 'counts from hourly counts.  Provide the ' +      \
                                 'required statistical parameters to execute ' +   \
                                 'the model.',
                 'version': '0.1'},
                 'sample': {},
                 'documentation': {'links': {'Minnesota Cycling Negative Binomial Model': None}},
                 'input': {'description': 'The indicated properties should be ' +   \
                                          'provided for each row of input data. ' + \
                                          ' Omitting a property will result in ' +  \
                                          'an incomplete execution of the model ' + \
                                          'as the missing property and its ' +      \
                                          'coefficients will be omitted from the' + \
                                          ' model entirely.',
                           'properties': {'constant': {'description': 'Constant value',
                                                       'type': 'number',
                                                       'default': 4.766,
                                                       'required': True},
                                          'Pctnonwhite': {'description': 'Percentage of neighborhood residents that are non-white',
                                                          'type': 'property',
                                                          'required': True, },
                                          'PctU5_O65': {'description': 'Percentage of neighborhood residents over 65 or under 5',
                                                        'type': 'property',
                                                        'required': True,},
                                          'Pctw4ormore': {'description': 'Percentage of neighborhood residents with a college education',
                                                          'type': 'property',
                                                          'required': True,},
                                          'MedHHInc': {'description': 'Median household income',
                                                       'type': 'property',
                                                       'required': True,},
                                          'Crime': {'description': 'Average number of violent crimes/year',
                                                    'type': 'property',
                                                    'required': True,},
                                          'PDperkm2': {'description': 'Population density in persons per square kilometer',
                                                       'type': 'property',
                                                       'required': True,},
                                          'LUMix': {'description': 'Measure of mixing of land uses (range 0-1)',
                                                    'type': 'property',
                                                    'required': True,},
                                          'WatDist_km': {'description': 'Distance from nearest body of water, in kilometers',
                                                         'type': 'property',
                                                         'required': True,},
                                          'CBDdist_km': {'description': 'Distance from central business district, kilometers',
                                                         'type': 'property',
                                                         'required': True,},
                                          'EmployAccess': {'description': 'Number of jobs accessible via transit.',
                                                           'type': 'property',
                                                           'required': True,},
                                          'Tmax': {'description': 'Recorded daily high temperature',
                                                   'type': 'property',
                                                   'required': True,},
                                          'Precip': {'description': 'Recorded precipitation',
                                                     'type': 'property',
                                                     'required': True,},
                                          'University': {'description': 'University district (1/0)',
                                                         'type': 'property',
                                                         'required': True,},
                                          'BusRoute': {'description': 'Presence of one of more bus routes (1/0)',
                                                       'type': 'property',
                                                       'required': True,},
                                          'Principal': {'description': 'Principal arterial street (1/0)',
                                                        'type': 'property',
                                                        'required': True,},
                                          'Arterial': {'description': 'Arterial street (1/0)',
                                                       'type': 'property',
                                                       'required': True,},
                                          'Collector': {'description': 'Collector street  (1/0)',
                                                        'type': 'property',
                                                        'required': True,},
                                          'Local': {'description': 'Local street (1/0)',
                                                    'type': 'property',
                                                    'required': True,},
                                          'OnstreetFacility': {'description': 'On street bicycle facility (1/0)',
                                                               'type': 'property',
                                                               'required': True,},
                                          'OffstreetTrail': {'description': 'Off-street trail (1/0)',
                                                             'type': 'property',
                                                             'required': True,},
                                          'Year': {'description': 'Level variable indicating year count occurred (offset from year 2007)',
                                                   'type': 'property',
                                                   'required': True,},
                                          'Pctnonwhite_coeff': {'description': 'Coefficient used for OLS Pctnonwhite property',
                                                                'type': 'number',
                                                                'default': .514,
                                                                'required': True,},
                                          'PctU5_O65_coeff': {'description': 'Coefficient used for OLS PctU5_O65 property',
                                                              'type': 'number',
                                                              'default': .640,
                                                              'required': True,},
                                          'Pctw4ormore_coeff': {'description': 'Coefficient used for OLS Pctw4ormore property',
                                                                'type': 'number',
                                                                'default': 1.348,
                                                                'required': True,},
                                          'MedHHInc_coeff': {'description': 'Coefficient used for OLS MedHHInc property',
                                                             'type': 'number',
                                                             'default': -.0089,
                                                             'required': True,},
                                          'Crime_coeff': {'description': 'Coefficient used for OLS Crime property',
                                                          'type': 'number',
                                                          'default': -0.0008,
                                                          'required': True,},
                                          'PDperkm2_coeff': {'description': 'Coefficient used for OLS PDperkm2 property',
                                                             'type': 'number',
                                                             'default': -0.00003,
                                                             'required': True,},
                                          'LUMix_coeff': {'description': 'Coefficient used for OLS LUMix property',
                                                          'type': 'number',
                                                          'default': .613,
                                                          'required': True,},
                                          'WatDist_km_coeff': {'description': 'Coefficient used for OLS WatDist_km property',
                                                               'type': 'number',
                                                               'default': .056,
                                                               'required': True,},
                                          'CBDdist_km_coeff': {'description': 'Coefficient used for OLS CBDdist_km property',
                                                               'type': 'number',
                                                               'default': -0.196,
                                                               'required': True,},
                                          'EmployAccess_coeff': {'description': 'Coefficient used for OLS EmployAccess property',
                                                                 'type': 'number',
                                                                 'default': 0.000005,
                                                                 'required': True,},
                                          'Tmax_coeff': {'description': 'Coefficient used for OLS Tmax property',
                                                         'type': 'number',
                                                         'default': -0.015,
                                                         'required': True,},
                                          'Precip_coeff': {'description': 'Coefficient used for OLS Precip property',
                                                           'type': 'number',
                                                           'default': -0.163,
                                                           'required': True,},
                                          'University_coeff': {'description': 'Coefficient used for OLS University property',
                                                               'type': 'number',
                                                               'default': 0,
                                                               'required': True,},
                                          'BusRoute_coeff': {'description': 'Coefficient used for OLS BusRoute property',
                                                             'type': 'number',
                                                             'default': 0,
                                                             'required': True,},
                                          'Principal_coeff': {'description': 'Coefficient used for OLS Principal property',
                                                              'type': 'number',
                                                              'default': -.275,
                                                              'required': True,},
                                          'Arterial_coeff': {'description': 'Coefficient used for OLS Arterial property',
                                                             'type': 'number',
                                                             'default': .396,
                                                             'required': True,},
                                          'Collector_coeff': {'description': 'Coefficient used for OLS Collector property',
                                                              'type': 'number',
                                                              'default': .960,
                                                              'required': True,},
                                          'Local_coeff': {'description': 'Coefficient used for OLS Local property',
                                                          'type': 'number',
                                                          'default': 0,
                                                          'required': True,},
                                          'OnstreetFacility_coeff': {'description': 'Coefficient used for OLS OnstreetFacility property',
                                                                     'type': 'number',
                                                                     'default': .317,
                                                                     'required': True,},
                                          'OffstreetTrail_coeff': {'description': 'Coefficient used for OLS OffstreetTrail property',
                                                                   'type': 'number',
                                                                   'default': 1.463,
                                                                   'required': True,},
                                          'Year_coeff': {'description': 'Coefficient used for OLS Year property',
                                                         'type': 'number',
                                                         'default': .045,
                                                         'required': True,},
                                         }}
                }